-- Setup DB Script for MemoraAI
-- Run this in your Supabase SQL Editor to initialize the database tables.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. REFRESH TOKENS TABLE
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    token_hash VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. IMAGES TABLE
CREATE TABLE IF NOT EXISTS images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    storage_path VARCHAR(512) NOT NULL,                    -- Path in Supabase bucket 'Memora ai'
    public_url VARCHAR(512) NOT NULL,                      -- Public accessible URL
    mime_type VARCHAR(100),
    size_bytes INT,
    width INT,
    height INT,
    scene_description TEXT,                                -- Generated by Claude on Bedrock
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,             -- Soft delete flag
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,      -- Timestamp when soft deleted
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. FACE LABELS TABLE
CREATE TABLE IF NOT EXISTS face_labels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,                            -- e.g., "Mother", "John"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_label UNIQUE (user_id, name)
);

-- 5. DETECTED FACES TABLE
CREATE TABLE IF NOT EXISTS faces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    image_id UUID REFERENCES images(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    box_top INT NOT NULL,                                  -- Bounding box coordinates
    box_right INT NOT NULL,
    box_bottom INT NOT NULL,
    box_left INT NOT NULL,
    embedding_vector BYTEA,                                -- 128-dimensional float32 array serialized
    face_thumbnail_url VARCHAR(512),                       -- URL to thumbnail in Supabase bucket
    label_id UUID REFERENCES face_labels(id) ON DELETE SET NULL, -- Null if not recognized yet
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. FACE QUEUE TABLE
CREATE TABLE IF NOT EXISTS face_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    face_id UUID REFERENCES faces(id) ON DELETE CASCADE UNIQUE NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    temporary_name VARCHAR(100) UNIQUE NOT NULL,           -- e.g., "Subject_Face_88e3"
    status VARCHAR(50) DEFAULT 'pending' NOT NULL,         -- 'pending', 'resolved'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- INDEXES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_images_user_active ON images(user_id) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_images_user_bin ON images(user_id) WHERE is_deleted = TRUE;
CREATE INDEX IF NOT EXISTS idx_faces_image ON faces(image_id);
CREATE INDEX IF NOT EXISTS idx_face_queue_user_pending ON face_queue(user_id) WHERE status = 'pending';
